---
- name: Configure agent (Linux)
  ansible.builtin.include_tasks: linux/configure.yml
  when: ansible_facts.os_family != "Windows"

- name: Configure agent (Windows)
  ansible.builtin.include_tasks: windows/configure.yml
  when: ansible_facts.os_family == "Windows"
