---
- name: Install sensu-go-agent binary
  ansible.builtin.include_role:
    name: install
  vars:
    components: [sensu-go-agent] # noqa: var-naming[no-role-prefix]

- name: Inform restart handler that we are in charge of the agent service
  ansible.builtin.set_fact:
    manage_sensu_agent_service: true

- name: Configure the agent
  ansible.builtin.include_tasks: configure.yml

- name: Start the agent
  ansible.builtin.include_tasks: start.yml
