namespace: sensu
name: sensu_go
version: 0.7.5

authors:
  - Paul Arthur <paul.arthur@flowerysong.com> (@flowerysong)
  - XLAB Steampunk <steampunk@xlab.si>

tags:
  - sensu
  - sensugo
  - monitoring

readme: README.rst
license_file: COPYING
description: Roles and modules for installing and using Sensu Go

repository: https://github.com/sensu/sensu-go-ansible
issues: https://github.com/sensu/sensu-go-ansible/issues
