namespace: sensu
name: sensu_go
version: 1.9.3

authors:
  - Paul Arthur <paul.arthur@flowerysong.com> (@flowerysong)
  - XLAB Steampunk <steampunk@xlab.si>

tags:
  - sensu
  - sensugo
  - monitoring

readme: README.md
license_file: COPYING
description: Roles and modules for installing and using Sensu Go

repository: https://github.com/sensu/sensu-go-ansible
issues: https://github.com/sensu/sensu-go-ansible/issues
documentation: https://sensu.github.io/sensu-go-ansible/
homepage: https://sensu.github.io/sensu-go-ansible/
