---
- name: Install sensu-go-backend binary
  include_role:
    name: install
  vars:
    components: [sensu-go-backend]

- name: Configure sensu-backend (/etc/sensu/backend.yml)
  template:
    src: backend.yml.j2
    dest: /etc/sensu/backend.yml
    # Keep this in sync with what the backend service is running as from packager
    owner: sensu
    group: sensu
    mode: '0600'
  notify: Restart backend
  tags: [configure_backend]

- name: Start sensu-backend
  service:
    name: sensu-backend
    state: started
    enabled: yes
  tags: [run_backend]
