---
- name: Install sensu-go-backend binary
  ansible.builtin.include_role:
    name: install
  vars:
    components: [sensu-go-backend] # noqa: var-naming[no-role-prefix]

- name: Inform restart handler that we are in charge of the backend service
  ansible.builtin.set_fact:
    manage_sensu_backend_service: true

- name: Configure the backend
  ansible.builtin.include_tasks: configure.yml

- name: Start the backend
  ansible.builtin.include_tasks: start.yml
