---
- name: Install sensu-backend binary
  hosts: backends
  roles:
     - sensu.sensu_go.install
  vars:
    components: [ sensu-go-backend ]

- name: Install sensu-agent binary from testing repository
  hosts: agents
  roles:
     - sensu.sensu_go.install
  vars:
    components: [ sensu-go-agent ]
    channel: testing

- name: Install sensuctl binary
  hosts: localhost
  roles:
     - sensu.sensu_go.install
  vars:
    components: [ sensu-go-cli ]
