---
- name: Install latest component version
  apt:
    name: "{{ item }}"
    state: latest
  when: version == "latest"
  loop: "{{ components }}"

- name: Install specific component version ({{ version }})
  apt:
    name: "{{ item }}={{ version }}-*"
    state: present
    force: true
  when: version != "latest"
  loop: "{{ components }}"
