---
- name: Install component
  apt:
    name: "{{ 'apt' | sensu.sensu_go.package_name(item, version, build) }}"
    # Apt only supports latest state on names with no version suffix.
    state: "{{ (version == 'latest') | ternary('latest', 'present') }}"
  loop: "{{ components }}"
