---
# Why did we kill the 403 (package installs should not use latest) check?
# Because we really do want to be able to upgrade the packages to the latest
# stable version.
- name: Install latest component version
  yum:
    name: "{{ item }}"
    state: latest  # noqa 403
  when: version == "latest"
  loop: "{{ components }}"

- name: Install specific component version ({{ version }})
  yum:
    name: "{{ item }}-{{ version }}"
    state: present
    allow_downgrade: true
  when: version != "latest"
  loop: "{{ components }}"
