Vagrant.configure("2") do |config|
  # Common config
  config.vm.box = "centos/7"
  config.vm.provision(
    "shell",
    inline: "cat /vagrant/demo.pub >> /home/vagrant/.ssh/authorized_keys"
  )

  # Backend
  config.vm.define("backend") do |backend|
    backend.vm.hostname = "backend"
    backend.vm.network "private_network", ip: "192.168.50.20"
    backend.vm.network "forwarded_port", guest: 3000, host: 13000
    backend.vm.provider("virtualbox") do |v|
      v.memory = 2048
      v.cpus = 1
    end
  end

  # Monitored VMs
  2.times do |i|
    config.vm.define("agent#{i}") do |agent|
      agent.vm.box = i % 2 == 0 ? "centos/7" : "debian/stretch64"
      agent.vm.hostname = "agent#{i}"
      agent.vm.network "private_network", ip: "192.168.50.3#{i}"
      agent.vm.provider("virtualbox") do |v|
        v.memory = 1024
        v.cpus = 1
      end
    end
  end
end
