Vagrant.configure("2") do |config|
  # Common config
  config.vm.box = "centos/7"
  config.vm.provision(
    "shell",
    inline: "cat /vagrant/demo.pub >> /home/vagrant/.ssh/authorized_keys"
  )

  # VM-specific config
  config.vm.define("backend") do |backend|
    backend.vm.hostname = "backend"
    backend.vm.network "private_network", ip: "192.168.50.4"
    backend.vm.provider("virtualbox") do |v|
      v.memory = 2048
      v.cpus = 1
    end
  end
end
