modules := $(wildcard ../plugins/modules/*.py)
module_docs := $(modules:../plugins/modules/%.py=source/modules/%.rst)

.PHONY: all
docs: $(module_docs)
	$(MAKE) html

.PHONY: clean
clean:
	rm -rf build source/modules

source/modules/%.rst: ../plugins/modules/%.py ../plugins/doc_fragments/*.py
	mkdir -p source/modules
	ansible-doc-extractor source/modules $<
