# Copyright (c) 2019 Paul Arthur MacIain
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


class ModuleGroup(object):
    MODULES = [
        'flowerysong.sensu_go.sensu_go_asset_info',
        'flowerysong.sensu_go.sensu_go_check_info',
        'flowerysong.sensu_go.sensu_go_check',
        'flowerysong.sensu_go.sensu_go_entity_info',
        'flowerysong.sensu_go.sensu_go_entity',
        'flowerysong.sensu_go.sensu_go_event_info',
        'flowerysong.sensu_go.sensu_go_filter_info',
        'flowerysong.sensu_go.sensu_go_filter',
        'flowerysong.sensu_go.sensu_go_handler_info',
        'flowerysong.sensu_go.sensu_go_handler',
        'flowerysong.sensu_go.sensu_go_hook_info',
        'flowerysong.sensu_go.sensu_go_mutator_info',
        'flowerysong.sensu_go.sensu_go_namespace_info',
        'flowerysong.sensu_go.sensu_go_rolebinding_info',
        'flowerysong.sensu_go.sensu_go_rolebinding',
        'flowerysong.sensu_go.sensu_go_role_info',
        'flowerysong.sensu_go.sensu_go_role',
        'flowerysong.sensu_go.sensu_go_tessen',
        'flowerysong.sensu_go.sensu_go_user_info',
        'flowerysong.sensu_go.sensu_go_user',
        'sensu_go_asset_info',
        'sensu_go_check_info',
        'sensu_go_check',
        'sensu_go_entity_info',
        'sensu_go_entity',
        'sensu_go_event_info',
        'sensu_go_filter_info',
        'sensu_go_filter',
        'sensu_go_handler_info',
        'sensu_go_handler',
        'sensu_go_hook_info',
        'sensu_go_mutator_info',
        'sensu_go_namespace_info',
        'sensu_go_rolebinding_info',
        'sensu_go_rolebinding',
        'sensu_go_role_info',
        'sensu_go_role',
        'sensu_go_tessen',
        'sensu_go_user_info',
        'sensu_go_user',
    ]
