---
- name: Prepare package manager ({{ ansible_pkg_mgr }})
  include_tasks: '{{ ansible_pkg_mgr }}/prepare.yml'
  tags:
    - prepare_install
    - install

- name: Install components
  include_tasks: '{{ ansible_pkg_mgr }}/install.yml'
  tags:
    - install
