---
- name: Prepare package repositories
  ansible.builtin.include_tasks: repositories.yml
  when: ansible_facts.os_family != "Windows"  # No repo concept on Windows

- name: Install selected packages
  ansible.builtin.include_tasks: packages.yml
